import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.css'
import { ClerkProvider, SignIn, SignedOut } from '@clerk/nextjs'
import { SignedIn } from '@clerk/nextjs'
import Navbar from '@/components/Navbar'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfit.className}>
          <SignedIn>
            <Navbar/>
            <div className='container mx-auto'>
              {children}
            </div>
          </SignedIn>
          <SignedOut>
            <SignIn/>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  )
}
